### ISSUE TITLE
gNPSI dial-in, dial-out  or both?

### ISSUE THREAD

**Issue by dplore** [openconfig/gnpsi#9]
Hi, it appears that gNPSI is only intended for dial-in usage, ie: where the collector opens a connection to a device.  Is that true?

If so, I think it is helpful to explicitly state this in the README for gNPSI.  Since the protocols it is replacing all open connections sourced from the device, it is helpful to make this point clear in gNPSI.

**Comment by dplore** [comment]
Reference: https://github.com/openconfig/public/pull/1085

**Comment by RazorBach** [comment]
I think for today's use case, Yes. It's always the collector initiates the collection.

@kishanps for confirmation.

**Comment by kishanps** [comment]
Yes, that's right, gNPSI on the switch is designed only for dial-in by the collector.

**Comment by RazorBach** [comment]
Close this issue now, feel free to reopen if you have more questions.
